apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway
spec:
  type: NodePort
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 3000
      nodePort: 30080  # Minikube irá mapear essa porta
  selector:
    app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: users-service
---
apiVersion: v1
kind: Service
metadata:
  name: request-service
  labels:
    app: request-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3002
      protocol: TCP
      targetPort: 3002
  selector:
    app: request-service
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-eco-tech
  labels:
    app: postgres-eco-tech
spec:
  type: ClusterIP
  ports:
    - name: db
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres-eco-tech
